import io
import logging
from collections.abc import AsyncIterator

import edge_tts
from .base import BaseTTS
from ..config import settings

logger = logging.getLogger(__name__)

class EdgeTTSEngine(BaseTTS):
    """Async TTS using Microsoft Edge TTS (edge-tts library).
    
    Free, no API key required. Produces MP3 bytes directly.
    Supports 300+ voices: https://github.com/rany2/edge-tts
    """

    def __init__(self):
        self._voice = settings.EDGE_TTS_VOICE
        logger.info("Edge-TTS ready: voice=%s", self._voice)

    async def synthesize_stream(self, text: str) -> AsyncIterator[bytes]:
        """Yield MP3 chunks as they are generated by Edge TTS."""
        logger.info("[EdgeTTSEngine] synthesizing text: %r", text)
        communicate = edge_tts.Communicate(text, self._voice)
        async for chunk in communicate.stream():
            if chunk["type"] == "audio":
                yield chunk["data"]

    async def synthesize(self, text: str) -> bytes:
        """Convert text to MP3 bytes using Edge TTS."""
        logger.info("[EdgeTTSEngine] synthesizing text: %r", text)
        buf = io.BytesIO()
        async for chunk in self.synthesize_stream(text):
            buf.write(chunk)
        return buf.getvalue()
